import 'package:flutter/material.dart';

class MyMusicList extends StatefulWidget {
  const MyMusicList({super.key});

  @override
  State<MyMusicList> createState() => _MyMusicListState();
}

class _MyMusicListState extends State<MyMusicList> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.grey.shade900,
      appBar: AppBar(
          backgroundColor: Colors.black,
          actions: [
            InkWell(
              onTap: () {},
              child: Icon(
                Icons.search_sharp,
                color: Colors.grey.shade400,
                size: 28,
              ),
            ),
            const SizedBox(
              width: 5,
            ),
            InkWell(
              onTap: () {},
              child: Icon(
                Icons.more_vert_sharp,
                color: Colors.grey.shade400,
                size: 28,
              ),
            ),
            const SizedBox(
              width: 12,
            ),
          ],
          title: RichText(
              text: TextSpan(children: [
            TextSpan(
                text: "SAMSUNG  ",
                style: TextStyle(
                    color: Colors.grey.shade400,
                    fontSize: 18,
                    fontWeight: FontWeight.w900)),
            TextSpan(
                text: "Music",
                style: TextStyle(
                    color: Colors.grey.shade400,
                    fontSize: 18,
                    fontWeight: FontWeight.bold)),
          ]))),
      body: ListView.builder(
        itemCount: artistNames.length,
        itemBuilder: (context, index) {
          return Column(
            children: [
              Padding(
                padding: const EdgeInsets.all(8.0),
                child: Row(
                  children: [
                    const Expanded(
                      flex: 1,
                      child: Icon(
                        Icons.library_music_outlined,
                        color: Colors.white,
                        size: 40,
                      ),
                    ),
                    const SizedBox(
                      width: 20,
                    ),
                    Expanded(
                        flex: 8,
                        child: Column(
                          children: [
                            Row(
                              children: [
                                Text(
                                  songNames[index],
                                  overflow: TextOverflow.ellipsis,
                                  textAlign: TextAlign.left,
                                  style: const TextStyle(
                                      color: Colors.white, fontSize: 22),
                                ),
                              ],
                            ),
                            Row(
                              children: [
                                Text(
                                  artistNames[index],
                                  style: TextStyle(
                                      color: Colors.grey.shade400,
                                      fontSize: 16),
                                ),
                              ],
                            ),
                          ],
                        )),
                    Expanded(
                      flex: 1,
                      child: InkWell(
                        onTap: () {},
                        child: Icon(
                          Icons.more_vert_sharp,
                          color: Colors.grey.shade400,
                          size: 28,
                        ),
                      ),
                    )
                  ],
                ),
              ),
              Divider(
                color: Colors.grey.shade400,
                thickness: 2,
                indent: 65,
                endIndent: 20,
              ),
            ],
          );
        },
      ),
    );
  }
}

final songNames = [
  "Blinding Lights",
  "Shape of You",
  "Levitating",
  "Stay",
  "Good 4 U",
  "As It Was",
  "Industry Baby",
  "Save Your Tears",
  "Bad Habits",
  "Peaches",
  "Kiss Me More",
  "Montero",
  "Watermelon Sugar",
  "Mood",
  "Heat Waves",
  "Take My Breath",
  "Shivers",
  "Stay",
  "Levitating",
  "Butter",
  "Enemy",
  "Blinding Lights",
  "Adore You",
  "Don't Start Now",
  "Circles",
  "Dynamite",
  "Lose Control",
  "Sicko Mode",
  "Can't Stop the Feeling!",
  "Happier Than Ever",
  "Stupid",
  "Good 4 U",
  "Old Town Road",
  "Senorita",
  "Uptown Funk",
  "Shallow",
  "The Less I Know the Better",
  "Bad Guy",
  "Thank U, Next",
  "Lose You to Love Me",
  "Savage Love",
  "Peaches",
  "Rolling in the Deep",
  "Closer",
  "All of Me",
  "Bad Romance",
  "Take On Me",
  "Thriller",
  "Levitating",
  "Shallow",
  "Dance Monkey",
  "Roar",
  "Can't Feel My Face",
  "Perfect",
  "Feel It Still",
  "Havana",
  "Counting Stars",
  "Blinding Lights",
  "Someone Like You",
  "Radioactive",
  "Call Me Maybe",
  "Let It Be",
  "The Middle",
  "Shake It Off",
  "Titanium",
  "Faded",
  "Stay",
  "Sorry",
  "Senorita",
  "Believer",
  "Smells Like Teen Spirit",
  "Highway to Hell",
  "Bohemian Rhapsody",
  "Back In Black",
  "Sweet Child O' Mine",
  "Imagine",
  "Don't Stop Believin'",
  "Let It Go",
  "Rolling Stone",
  "The Way You Make Me Feel",
  "Born to Run",
  "Livin' On a Prayer",
  "In the End",
  "Eye of the Tiger",
  "Radioactive",
  "Take Me to Church",
  "Get Lucky",
  "Gangnam Style",
  "I Will Always Love You",
  "Single Ladies",
  "With or Without You",
  "Dream On",
  "Stayin' Alive",
  "I Wanna Dance with Somebody",
  "Africa",
  "What a Wonderful World",
  "Let Her Go",
  "Rolling Stone",
  "Somebody That I Used to Know",
  "Bleeding Love",
  "Rock You Like a Hurricane",
  "Counting Stars",
  "Perfect",
  "Old Town Road",
  "All of Me",
  "The Scientist",
  "My Heart Will Go On",
  "Bohemian Rhapsody",
  "American Pie"
];

final artistNames = [
  "The Weeknd",
  "Ed Sheeran",
  "Dua Lipa",
  "The Kid LAROI, Justin Bieber",
  "Olivia Rodrigo",
  "Harry Styles",
  "Lil Nas X, Jack Harlow",
  "The Weeknd",
  "Ed Sheeran",
  "Justin Bieber",
  "Doja Cat",
  "Lil Nas X",
  "Harry Styles",
  "24kGoldn, Iann Dior",
  "Glass Animals",
  "The Weeknd",
  "Ed Sheeran",
  "The Kid LAROI",
  "BTS",
  "Imagine Dragons",
  "The Weeknd",
  "Harry Styles",
  "Dua Lipa",
  "Post Malone",
  "BTS",
  "Shawn Mendes, Camila Cabello",
  "Migos",
  "Justin Timberlake",
  "Billie Eilish",
  "Ava Max",
  "Olivia Rodrigo",
  "Lil Nas X",
  "Camila Cabello, Shawn Mendes",
  "Mark Ronson, Bruno Mars",
  "Lady Gaga, Bradley Cooper",
  "Tame Impala",
  "Billie Eilish",
  "Ariana Grande",
  "Selena Gomez",
  "Jawsh 685, Jason Derulo",
  "Adele",
  "Ariana Grande",
  "Adele",
  "Imagine Dragons",
  "John Legend",
  "Lady Gaga",
  "Imagine Dragons",
  "The Chainsmokers",
  "Taylor Swift",
  "David Guetta, Sia",
  "Alan Walker",
  "Ed Sheeran",
  "Dua Lipa",
  "Ariana Grande",
  "Tones and I",
  "Katy Perry",
  "The Weeknd",
  "The Beatles",
  "Maroon 5",
  "Elton John",
  "Post Malone",
  "The Rolling Stones",
  "Michael Jackson",
  "Taylor Swift",
  "Led Zeppelin",
  "Bruce Springsteen",
  "Linkin Park",
  "Survivor",
  "Imagine Dragons",
  "Hozier",
  "Daft Punk",
  "PSY",
  "Whitney Houston",
  "Beyoncé",
  "U2",
  "Aerosmith",
  "Bee Gees",
  "Whitney Houston",
  "Toto",
  "Louis Armstrong",
  "Passenger",
  "Gotye",
  "Leona Lewis",
  "Scorpions",
  "OneRepublic",
  "Ed Sheeran",
  "Coldplay",
  "Celine Dion",
  "Queen",
  "Don McLean",
  "Disney's Frozen Soundtrack",
  "Queen",
  "Led Zeppelin",
  "Bob Dylan"
];
